version: "3"

volumes:
  prometheus_data:
  grafana_data:
  postgres_volume_local:
  redis-data:
  # postgres_volume_prod:

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    
  pg-local:
    image: postgres:16-alpine3.20
    env_file:
      - "local.env"
    ports:
      - "50001:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  # pg-prod:
  #   image: postgres:16-alpine3.20
  #   env_file:
  #     - "prod.env"
  #   ports:
  #     - "50002:5432"
  #   volumes:
  #     - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # migrator-prod:
  #   build:
  #     context: .
  #     dockerfile: migration_prod.dockerfile
  #   restart: on-failure
  #   environment:
  #     DB_HOST: pg-prod
